language: node_js
node_js:
  - "node"
  - "lts/*"
env:
  global:
    - CC_TEST_REPORTER_ID=db4586c489860b566f93a090c97dcafa022a582fb36e33a5ad314848ca8ef1e9
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
